######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 4 22:50:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qssnake.hpp
SOURCES += main.cpp qssnake.cpp
